"""optional empl

Revision ID: 02f397b0998f
Revises: 7e504dc702dd
Create Date: 2022-08-03 15:10:10.059494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02f397b0998f'
down_revision = '7e504dc702dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
