"""selectin

Revision ID: 07c685bebc8e
Revises: f0ea243d0da0
Create Date: 2022-08-03 14:35:39.355402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c685bebc8e'
down_revision = 'f0ea243d0da0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
