"""optional empl

Revision ID: 13f96eaaf9b4
Revises: e5fedde3ad0a
Create Date: 2022-08-03 16:45:35.146368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f96eaaf9b4'
down_revision = 'e5fedde3ad0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
