"""optional empl

Revision ID: 1df78527606c
Revises: 97b797f6b98d
Create Date: 2022-08-03 16:57:55.525396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df78527606c'
down_revision = '97b797f6b98d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
