"""optional empl

Revision ID: 2033c8a3424f
Revises: a881d2a2414b
Create Date: 2022-08-03 15:44:11.785865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2033c8a3424f'
down_revision = 'a881d2a2414b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_id_person_fkey', 'employee', type_='foreignkey')
    op.drop_column('employee', 'id_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('id_person', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('employee_id_person_fkey', 'employee', 'person', ['id_person'], ['id'])
    # ### end Alembic commands ###
