"""optional empl

Revision ID: 36b80b758bfe
Revises: 7aa7b7082a84
Create Date: 2022-08-03 15:19:06.082683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b80b758bfe'
down_revision = '7aa7b7082a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
