"""optional empl

Revision ID: 48012a1feb1a
Revises: 55e44cdb85f3
Create Date: 2022-08-03 17:08:52.776962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48012a1feb1a'
down_revision = '55e44cdb85f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
