"""optional empl

Revision ID: 4846dd0234a5
Revises: dfefa7dd144c
Create Date: 2022-08-03 15:53:12.127667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4846dd0234a5'
down_revision = 'dfefa7dd144c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
