"""optional empl

Revision ID: 53d83d0117f0
Revises: 9f4f5f5c7131
Create Date: 2022-08-03 16:12:27.431046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d83d0117f0'
down_revision = '9f4f5f5c7131'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
