"""optional empl

Revision ID: 663b23c6ece5
Revises: 2033c8a3424f
Create Date: 2022-08-03 15:47:46.433021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b23c6ece5'
down_revision = '2033c8a3424f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
