"""selectin

Revision ID: 7e504dc702dd
Revises: 07c685bebc8e
Create Date: 2022-08-03 14:36:51.713371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e504dc702dd'
down_revision = '07c685bebc8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
