"""optional empl

Revision ID: 86cf9441922f
Revises: 8b829008c5d1
Create Date: 2022-08-03 16:43:05.067011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cf9441922f'
down_revision = '8b829008c5d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
