"""optional empl

Revision ID: 921fdfebae92
Revises: d1aafc50e60e
Create Date: 2022-08-03 16:15:43.036787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921fdfebae92'
down_revision = 'd1aafc50e60e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
