"""optional empl

Revision ID: 96797638c7ff
Revises: 13f96eaaf9b4
Create Date: 2022-08-03 16:46:53.468288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96797638c7ff'
down_revision = '13f96eaaf9b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
