"""optional empl

Revision ID: 97b797f6b98d
Revises: 71bcff377813
Create Date: 2022-08-03 16:56:04.792081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b797f6b98d'
down_revision = '71bcff377813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
