"""optional empl

Revision ID: 9f4f5f5c7131
Revises: e436aaeca052
Create Date: 2022-08-03 16:11:53.400104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4f5f5c7131'
down_revision = 'e436aaeca052'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
