"""optional empl

Revision ID: a881d2a2414b
Revises: ec71cc17ec08
Create Date: 2022-08-03 15:43:29.177789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a881d2a2414b'
down_revision = 'ec71cc17ec08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
