"""empl relationship

Revision ID: b00ff25a1787
Revises: ff106e0d8b72
Create Date: 2022-08-03 13:53:18.117074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b00ff25a1787'
down_revision = 'ff106e0d8b72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
