"""optional empl

Revision ID: b7760fd233c7
Revises: d67252cda433
Create Date: 2022-08-03 17:03:58.242489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7760fd233c7'
down_revision = 'd67252cda433'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
