"""optional empl

Revision ID: bbb216539eaa
Revises: 36b80b758bfe
Create Date: 2022-08-03 15:25:33.869445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb216539eaa'
down_revision = '36b80b758bfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
