"""new struct

Revision ID: bfd13119e23d
Revises: 
Create Date: 2022-08-05 06:18:37.823572

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd13119e23d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id_person', sa.Integer(), nullable=True),
    sa.Column('id_department', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('dismissal_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['id_person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('person')
    # ### end Alembic commands ###
