"""optional empl

Revision ID: c6c1ec8c0e85
Revises: bbb216539eaa
Create Date: 2022-08-03 15:31:05.969255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c1ec8c0e85'
down_revision = 'bbb216539eaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
