"""integer

Revision ID: ccf9ae13aa62
Revises: 
Create Date: 2022-08-03 12:10:52.692534

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf9ae13aa62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id_organisation', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('Name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('Description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_organisation')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=False),
    sa.Column('id_person', sa.Integer(), nullable=True),
    sa.Column('id_department', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_department'], ['department.id'], ),
    sa.ForeignKeyConstraint(['id_person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('person')
    op.drop_table('department')
    # ### end Alembic commands ###
