"""optional empl

Revision ID: d1aafc50e60e
Revises: 53d83d0117f0
Create Date: 2022-08-03 16:14:22.015175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1aafc50e60e'
down_revision = '53d83d0117f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
