"""optional empl

Revision ID: d2aa55d46073
Revises: e1846999b4b2
Create Date: 2022-08-03 17:30:58.456922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2aa55d46073'
down_revision = 'e1846999b4b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('hire_date', sa.Date(), nullable=True))
    op.add_column('employee', sa.Column('dismissal_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'dismissal_date')
    op.drop_column('employee', 'hire_date')
    # ### end Alembic commands ###
