"""optional empl

Revision ID: dfefa7dd144c
Revises: fb5098db1d36
Create Date: 2022-08-03 15:53:06.746239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfefa7dd144c'
down_revision = 'fb5098db1d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
