"""optional empl

Revision ID: e1846999b4b2
Revises: 48012a1feb1a
Create Date: 2022-08-03 17:17:50.141538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1846999b4b2'
down_revision = '48012a1feb1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
