"""optional empl

Revision ID: e436aaeca052
Revises: 4846dd0234a5
Create Date: 2022-08-03 16:03:28.555130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e436aaeca052'
down_revision = '4846dd0234a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
