"""optional empl

Revision ID: e5fedde3ad0a
Revises: 86cf9441922f
Create Date: 2022-08-03 16:43:33.325824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fedde3ad0a'
down_revision = '86cf9441922f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
