"""optional empl

Revision ID: ec71cc17ec08
Revises: c6c1ec8c0e85
Create Date: 2022-08-03 15:40:09.798145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec71cc17ec08'
down_revision = 'c6c1ec8c0e85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
