"""empl relationship

Revision ID: f0ea243d0da0
Revises: f365147a6188
Create Date: 2022-08-03 14:28:39.849604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ea243d0da0'
down_revision = 'f365147a6188'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
