"""empl relationship

Revision ID: f365147a6188
Revises: b00ff25a1787
Create Date: 2022-08-03 14:21:48.134474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f365147a6188'
down_revision = 'b00ff25a1787'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
