"""optional empl

Revision ID: fb5098db1d36
Revises: 663b23c6ece5
Create Date: 2022-08-03 15:51:00.984062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5098db1d36'
down_revision = '663b23c6ece5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('id_person', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'person', ['id_person'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'id_person')
    # ### end Alembic commands ###
