"""new

Revision ID: ff106e0d8b72
Revises: ccf9ae13aa62
Create Date: 2022-08-03 12:23:32.337312

"""
from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff106e0d8b72'
down_revision = 'ccf9ae13aa62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('department', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('department', 'Description')
    op.drop_column('department', 'Name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('Name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('department', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('department', 'description')
    op.drop_column('department', 'name')
    # ### end Alembic commands ###
